##
# @file
# Some util functions that are used in the morphological evolution part and/or coevolution.py.
#
import locale
import time
from xml.dom import minidom

import numpy as np

from coevolution.arm import Arm
from util.config import get_config


def generate_arms(amount: int):
    """! Generate a list of initial random arms with random genome.
    @param amount: Amount of arms needed.
    @return List of arms.
    """
    return [Arm() for _ in range(amount)]


def alternate(list_to_alternate, times):
    """! Function to make an alternation of a list for x items.
    Example what = [1,2,3,4] times = 6 -> [1,2,3,4,1,2].
    @param list_to_alternate: The list that you want to alternate.
    @param times: Amount of times you want to alternate your items.
    @return Alternating list of size 'times'
    """
    alternations = []
    for alternation, _ in zip(alternate_infinite(list_to_alternate), range(times)):
        alternations.append(alternation)

    return alternations


def alternate_infinite(list_to_alternate):
    """! Function to make an alternation of a list on which you can iterate till infinity.
    Example list_to_alternate = [1,2,3,4] -> 1,2,3,4,1,2,3,4,1,2,3,4,...
    @param list_to_alternate: The list that you want to alternate.
    @return Next iteration.
    """
    current_index = 0
    while True:
        yield list_to_alternate[current_index]
        current_index = (current_index + 1) % len(list_to_alternate)


def normalize(list_to_normalize):
    """! Normalize a list.
    @param list_to_normalize: List to normalize.
    @return List in which items are normalized.
    """
    sum_list = sum(list_to_normalize) if sum(list_to_normalize) != 0 else 1
    return [i / sum_list for i in list_to_normalize]


def write_morphevo_benchmarks(arm: Arm):
    """! Output the benchmarks generated by morphevo code
    @param arm: Arm to save benchmarks for.
    """
    with open("morphevo-benchmarks.csv", 'a', encoding=locale.getpreferredencoding(False)) as file:
        module_lengths = np.array([])
        node = arm.genome.genotype_graph.anchor.next
        while node is not None:
            module_lengths = np.concatenate((module_lengths, node.lengths))
            node = node.next
        file.write(f'{arm.genome.workspace.side_length},{arm.genome.workspace.cube_offset},'
                   f'{sum(module_lengths)},{arm.genome.amount_of_modules},'
                   f'{arm.genome.workspace.calculate_coverage()}\n')


def save_genome(arm: Arm, label: str):
    """! Save the urdf of an arm.
    @param arm: Arm to save genome for.
    @param label: Unique label to add to the end of the name.
    """
    filename = (f'output/{int(time.time())}-mu_{get_config().coevolution_parents}' +
                f'-lambda_{get_config().coevolution_children}-gamma_{get_config().gamma}-{label}.xml')

    xml_str = minidom.parseString(arm.urdf).toprettyxml(indent="    ")
    with open(filename, "w", encoding=locale.getpreferredencoding(False)) as f:
        f.write(xml_str)
