description: "Example config"

coevolution:
  generations: 200
  parents: 16
  rl_amount: 8
  rl_episodes: 60
  crossover_children: 4
  children: 16

morphevo:
  generations: 75
  parents: 16
  children: 16
  crossover_children: 2
  sample_size: 100
  workspace_type: "moved_cube"

  workspace_cube_offset: [0,5,9]
  workspace_side_length: 4
  chance_of_type_mutation: 0.15

rl:
  episodes: 60
  steps_per_episode: 1000

  gamma: 0.95
  eps_end: 0
  eps_decay: 0.99995
  batch_size: 4
  mem_size: 20
  eps_start: 1
  hidden_nodes: 64

  goal_bal_diameter: 0.6
