description: "Example config"

arm:
  minimum_amount_modules: 2
  maximum_amount_modules: 4
  length_lower_bound: 1
  length_upper_bound: 4
  movements: ['rotate', 'tilt']

mutation:
  standard_deviation_length: 0.4
  chance_module_drop: 0.10
  chance_module_add: 0.10
  chance_type_mutation: 0.05

coevolution:
  generations: 200
  parents: 8
  rl_amount: 8
  rl_episodes: 130 
  children: 6
  crossover_children: 2

morphevo:
  generations: 75
  parents: 8
  children: 8 
  crossover_children: 0
  sample_size: 10
  workspace_type: 'moved_cube'

  # small cube next to arm
  workspace_cube_offset: [0,5,9]
  workspace_side_length: 4 

  # cube over whole environment
  #workspace_cube_offset: [0,2,0]
  #workspace_side_length: 17.5


rl:
  episodes: 130
  steps_per_episode: 1000
  gamma: 0.99
  eps_end: 0.2
  eps_decay: 0.999995
  batch_size: 64
  mem_size: 1000
  eps_start: 1 
  hidden_nodes: 64
  goal_bal_diameter: 0.6
