description: "Example config"

coevolution:
  generations: 10
  parents: 8
  rl_amount: 16

morphevo:
  generations: 75
  parents: 8
  children: 5
  crossover_children: 3
  sample_size: 100
  workspace_type: "moved_cube"
  workspace_cube_offset: [0,0,0]
  workspace_side_length: 4

rl:
  gamma: 0.99
  eps_end: 0.1
  eps_decay: 0.999992
  batch_size: 64
  mem_size: 1000
  eps_start: 1
  hidden_nodes: 32

  workspace_discretization: 0.2
  goal_bal_diameter: 0.6
