description: "Example config"

coevolution:
  coevolution_generations: 10
  coevolution_parents: 8
  coevolution_rl_amount: 16

morphevo:
  evolution_generations: 75
  evolution_parents: 8
  evolution_children: 5
  crossover_children: 3
  workspace_type: "moved_cube"
  workspace_cube_offset: [0,10,10]
  workspace_side_length: 10
  # small cube next to arm
  # workspace_cube_offset: [0,3,7]
  # workspace_side_length: 5

rl:
  gamma: 0.8
  eps_end: 0.2
  eps_decay: 0.999994
  batch_size: 64
  mem_size: 1000
  eps_start: 1
  hidden_nodes: 64

  workspace_discretization: 0.2
  goal_bal_diameter: 0.6
