description: "Config for using different walls for training"

coevolution:
  generations: 200
  parents: 8
  rl_amount: 8
  rl_episodes: 130
  children: 6
  crossover_children: 2

morphevo:
  generations: 75
  parents: 8
  children: 4
  crossover_children: 2
  sample_size: 100
  workspace_type: "moved_cube"
  workspace_cube_offset: [0,8,10]
  workspace_side_length: 8
  chance_of_type_mutation: 0.15

  # cube over whole environment
  #workspace_cube_offset: [0,2,0]
  #workspace_side_length: 17.5


rl:
  episodes: 130
  steps_per_episode: 1000
  gamma: 0.99
  eps_end: 0.2
  eps_decay: 0.999995
  batch_size: 64
  mem_size: 1000
  eps_start: 1
  hidden_nodes: 64
  use_walls: True
  goal_bal_diameter: 0.6
